var layertree = [
    { id: 3, pId: 0, name: "底图", "nocheck": true, layerurl: "" },
    { id: 31, pId: 3, name: "卫星", layerurl: "1" },
    { id: 32, pId: 3, name: "交通", layerurl: "0" },
    { id: 33, pId: 3, name: "标注图层", layerurl: "3" }, 
	{ id: 1, pId: 0, name: "项目", "nocheck": true, layerurl: "" },
	//{ id: 11, pId: 1, name: "调查勘探项目", layerurl: "11" },
	//{ id: 12, pId: 1, name: "发掘项目", layerurl: "12" },
	{ id: 2, pId: 0, name: "总体规划", "nocheck": true, layerurl: "" },
	//{ id: 211, pId: 2, name: "临安城遗址范围图", layerurl: "211" },
	{ id: 212, pId: 2, name: "南宋已考古遗址遗迹图", layerurl: "ZTtest/NSYKGYZYJT/MapServer" },
	{ id: 213, pId: 2, name: "南宋临安城复原示意图", layerurl: "ZTtest/NSLACFYT/MapServer" },
	{ id: 214, pId: 2, name: "遗产构成图-遗址本体", layerurl: "ZTtest/YCGCT_YZBT/MapServer" },
	{ id: 215, pId: 2, name: "遗产构成图-历史环境要素", layerurl: "ZTtest/YCGCT_LSHJYS/MapServer" },
	{ id: 216, pId: 2, name: "遗产构成图-背景环境", layerurl: "ZTtest/YCGCT_BJHJ/MapServer" },
	//{ id: 217, pId: 2, name: "城墙遗址现状评估", layerurl: "217" },
	//{ id: 218, pId: 2, name: "城门遗址现状评估", layerurl: "218" },
	//{ id: 219, pId: 2, name: "历史道路现状评估", layerurl: "219" },
	//{ id: 221, pId: 2, name: "历史水系现状评估", layerurl: "221" },
	{ id: 222, pId: 2, name: "管理区划现状评估", layerurl: "ZTtest/GLQHXZT/MapServer" },
	{ id: 223, pId: 2, name: "保护区划图", layerurl: "ZTtest/BHQHT/MapServer" },
	//{ id: 224, pId: 2, name: "城墙遗址保护措施图", layerurl: "224" },
	//{ id: 225, pId: 2, name: "城门遗址保护措施图", layerurl: "225" },
	//{ id: 226, pId: 2, name: "历史道路保护措施图", layerurl: "226" },
	//{ id: 227, pId: 2, name: "历史水系保护措施图", layerurl: "227" },
	{ id: 228, pId: 2, name: "环境保护措施图", layerurl: "ZTtest/HJBHCST/MapServer" },
	{ id: 229, pId: 2, name: "展示规划图", layerurl: "ZTtest/ZSGHT/MapServer" },
	//{ id: 231, pId: 2, name: "山水城郭展示路线图", layerurl: "231" },
	{ id: 232, pId: 2, name: "展示线路与景观廊道规划图", layerurl: "ZTtest/ZSLXYJGLDGHT/MapServer" },
	//{ id: 233, pId: 2, name: "土地利用规划调整图", layerurl: "233" },
	{ id: 234, pId: 2, name: "公共交通规划图", layerurl: "ZTtest/GGJTGHT/MapServer" },
	//{ id: 235, pId: 2, name: "规划管理与保护区划关系图", layerurl: "235" },
	{ id: 236, pId: 2, name: "分期规划图", layerurl: "ZTtest/FQGHT/MapServer" },
	{ id: 237, pId: 2, name: "保护区划分图", layerurl: "ZTtest/BHQHT/MapServer" }
];